### PR TITLE
Export chat window as isolated component (WIP)

### PR DESCRIPTION
**Pull request by reichert621**
### WIP

Relates to https://github.com/papercups-io/chat-widget/issues/32 and https://github.com/papercups-io/chat-widget/issues/24

Will allow:
```js
import {ChatWidget, ChatWindow} from '@papercups-io/chat-widget';

// ...

<ChatWindow
  title='Welcome to Papercups!'
  subtitle='Ask us anything in the chat window 😊'
  primaryColor={primaryColor}
  accountId='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'
  greeting='Hi there! How can I help you?'
  newMessagePlaceholder='Start typing...'
/>
```

Screenshot (rendered in `div`):
Screen Shot 2020-08-26 at 10 02 42 PM

cc @shunkakinoki @fabiosantoscode

### CODE REVIEW

**Comment by reichert621** [comment]
(sorry for the delay on this @shunkakinoki -- I want to do a bit more cleanup/refactoring and testing before merging)

**Comment by shunkakinoki** [comment]
Thanks for the follow up @reichert621 !!!
It's completely fine, thank you really. You guys are seriously awesome!!!
I'll be happy to test out an alpha version if you could release a npm alpha version.

**Comment by reichert621** [comment]
sounds good, i'll keep you posted!

**Comment by reichert621** [comment]
(closing in favor of https://github.com/papercups-io/chat-widget/pull/43)

**Pull request closed without merging**
