### PR TITLE
[v1.1.0] Export `ChatWindow` as separate component

### PR DESCRIPTION
**Pull request by reichert621**
_If you want to try this out, install `"@papercups-io/chat-widget": "^1.1.0-beta.5"` and then `import {ChatWindow} from '@papercups-io/chat-widget'`_ 

(React props are the same as the `ChatWidget` component)

TODOs:
- [x] Fix scroll issue affecting parent content
- [x] Add prop to indicate that `ChatWindow` does not have any toggle-able behavior (i.e. disable certain actions in the `ChatWidgetContainer`)

This update will allow users to embed the chat window wherever they want!

Example:
Screen Shot 2020-09-04 at 10 28 16 PM

Can style with CSS classes, e.g.
```css
.Papercups-chatWindowContainer {
  border-radius: 4px;
  box-shadow: rgba(0, 0, 0, 0.16) 0px 5px 24px;
}
```

### CODE REVIEW

**Comment by shunkakinoki** [comment]
@reichert621 Thanks for the update!!! This is so awesome! Love Papercups

**Comment by reichert621** [comment]
hey @shunkakinoki -- you can try this out now if you'd like!

just install `"@papercups-io/chat-widget": "^1.1.0-beta.0"` and then import the component like so:
```js
import {ChatWindow} from '@papercups-io/chat-widget';
```

see https://github.com/papercups-io/chat-widget/pull/43/files#diff-46aa2125795b19b6f8ddd66b6aed296dR47 for an example :)

**Comment by joelrojo** [comment]
This is so dope! Any chance it would be possible to customize the css or styles within the Chat window? 

Would love to be able to create a custom look in dark mode for the entire chat functionality (since our app is dark mode only). Would be awesome to potentially even allow theming.

**Comment by reichert621** [comment]
@joelrojo if you wanna play around with it, the chat UI is hosted in this repo: https://github.com/papercups-io/chat-window

you can use the `iframeUrlOverride` prop to point to your own custom version of this if you want!

**Comment by joelrojo** [comment]
@reichert621 by theming I mean the ability to customize the chat window at a more granular level, and potentially do it in a way that is shareable so others can benefit from the custom styling. 

Love that is supports the `primaryColor` prop, but really looking to customize the chat bubble colors, background of the window (instead of just white) etc, and  even as far a custom fonts would be next level! 

I can envision a library of custom themes that your users/community builds that are easily importable. Could support custom css/scss/less imports or maybe just a simple object that has more options. So instead of just `primaryColor` prop it would be something like a `theme` prop which would support specific colors for each specific UI element:

```jsx
<ChatWidget
  theme={{
    operatorChatBubble: "#222222",
    userChatBubble: "#AAAAAA",
    headerFont: "absolute or relative url to custom font",
    chatFont: "...",
    ... // more specific options here
  }}
/>
```

Ultimately just trying to get the component to be as close to our apps brand/theme as possible. 

Thanks for building such a cool product!

**Comment by reichert621** [comment]
got it! makes a lot of sense 😄 I'd love to support that at some point!

**Pull request merged**
